- name: Deploy Selected Service
  hosts: all
  become: no
  tasks:
    - name: Pull the selected service image
      docker_image:
        name: "noamjorno/{{ selected_service }}"
        source: pull
        tag: latest

    - name: Stop and remove any existing app container
      docker_container:
        name: my-running-app  
        state: absent

    - name: Run the selected service
      docker_container:
        name: my-running-app  
        image: "noamjorno/{{ selected_service }}:latest"
        state: started
        ports:
          - "80:5000"